import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Aarogya Ropana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p align="center">आरोग्य रोपना&nbsp;</p>
          {/* <code className={styles.code}>Project By ETB12</code> */}
          <div>
            {/* <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            > */}
            {/* By{" "} */}
            {/* <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              /> */}
            {/* </a> */}
          </div>
        </div>
        <div>
          <code className={styles.code}>Project By ETB12...</code>
        </div>
        <div className={styles.des}>
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
          <p>
            Anandibai Gopalrao Joshi (31 March 1865 – 26 February 1887) was the
            first Indian female doctor of western medicine. She was the first
            woman from the erstwhile Bombay presidency of India to study and
            graduate with a two-year degree in western medicine in the United
            States. Her husband encouraged her to study medicine. In 1880 he
            sent a letter to Royal Wilder, a well-known American missionary,
            stating his wife&apos;s interest in inquiring about a suitable post
            in the US for herself.[8] Wilder published the correspondence in his
            Princeton&apos;s Missionary Review. Theodicia Carpenter, a resident
            of Roselle, New Jersey, happened to read it while waiting to see her
            dentist. Impressed by both Anandibai&apos;s desire to study
            medicine, and Gopalrao&apos;s support for his wife, she wrote to
            Anandibai. Carpenter and Anandibai developed a close friendship and
            came to refer to each other as &apos;aunt&apos; and
            &apos;niece.&apos; Later, Carpenter would host Anandibai in Rochelle
            during Joshi&apos;s stay in the U.S.[9][4] While the Joshi couple
            was in Calcutta, Anandibai&apos;s health was declining. She suffered
            from weakness, constant headaches, occasional fever, and sometimes
            breathlessness. Theodicia sent her medicines from America, without
            results. In 1883, Gopalrao was transferred to Serampore, and he
            decided to send Anandibai by herself to America for her medical
            studies despite her poor health.
          </p>
          <div className={styles.thirteen}>
            <Image
              className="imagee"
              src="/doc2.png"
              alt="13"
              width={290}
              height={290}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              New Patient <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Add a new patient, their symptoms and add it to the network.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Network <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about patients and their problems around the world.
            </p>
          </a>

          <a
            href="./chat"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              AI ChatAssistant <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Ask solutions to your problems to a friendly AI.
            </p>
          </a>

          {/* <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a> */}
        </div>
      </main>
    </>
  );
}
